function y = normalization(mu, parity, alpha)
y = (1/2).*2.^(-1/2).*(1+(-1).*parity).*(exp(1).^((-1).*alpha.^2).*(( ...
    -1).^mu.*cos(alpha.^2)+cosh(alpha.^2))).^(-1/2)+(1/2).*2.^(-1/2).* ...
    parity.*(exp(1).^((-1).*alpha.^2).*((-1).*(-1).^mu.*sin(alpha.^2)+ ...
    sinh(alpha.^2))).^(-1/2);
end