function y = Pc(x,alpha,gamma)
a   = x(1);
phi = x(2);
y   = (1+2.*a.*(1+(-1).*a.^2).^(1/2).*cos(alpha.^2).*cos(phi).*sech( ...
  alpha.^2)).^(-1).*((1/2).*(cos(alpha.^2.*(1+(-1).*gamma))+cosh( ...
  alpha.^2.*(1+(-1).*gamma))).*cosh(alpha.^2.*gamma).*sech(alpha.^2) ...
  .*(1+2.*a.*(1+(-1).*a.^2).^(1/2).*cos(alpha.^2.*gamma).*cos(phi).* ...
  sech(alpha.^2.*gamma))+(1/2).*sech(alpha.^2).*(1+(-2).*a.*(1+(-1) ...
  .*a.^2).^(1/2).*cos(phi).*csch(alpha.^2.*gamma).*sin(alpha.^2.* ...
  gamma)).*(sin(alpha.^2.*(1+(-1).*gamma))+sinh(alpha.^2.*(1+(-1).* ...
  gamma))).*sinh(alpha.^2.*gamma));
end