function y = defaultFidelity(x,alpha,gamma)
a   = x(1);
phi = x(2);
y   = (1+2.*a.*(1+(-1).*a.^2).^(1/2).*cos(alpha.^2).*cos(phi).*sech( ...
  alpha.^2)).^(-1).*((1/2).*(cos(alpha.^2.*(1+(-1).*gamma))+cosh( ...
  alpha.^2.*(1+(-1).*gamma))).*cosh(alpha.^2.*gamma).*sech(alpha.^2) ...
  .*(1+2.*a.*(1+(-1).*a.^2).^(1/2).*cos(alpha.^2.*gamma).*cos(phi).* ...
  sech(alpha.^2.*gamma))+(1/2).*((-1).*cos(alpha.^2.*(1+(-1).*gamma) ...
  )+cosh(alpha.^2.*(1+(-1).*gamma))).*cosh(alpha.^2.*gamma).*sech( ...
  alpha.^2).*(1+(-4).*a.^2.*(1+(-1).*a.^2).*cos(alpha.^2).^2.*cos( ...
  phi).^2.*sech(alpha.^2).^2).^(-1).*(1+(-2).*a.*(1+(-1).*a.^2).^( ...
  1/2).*cos(alpha.^2.*gamma).*cos(phi).*sech(alpha.^2.*gamma)).*((( ...
  -1)+2.*a.^2).^2+4.*a.^2.*(1+(-1).*a.^2).*cos(alpha.^2).^2.*sech( ...
  alpha.^2).^2.*sin(phi).^2)+(1/2).*sech(alpha.^2).*(((-1)+2.*a.^2) ...
  .^2+4.*a.^2.*(1+(-1).*a.^2).*cos(alpha.^2).^2.*cos(phi).^2.*sech( ...
  alpha.^2).^2).*(1+2.*a.*(1+(-1).*a.^2).^(1/2).*cos(phi).*csch( ...
  alpha.^2.*gamma).*sin(alpha.^2.*gamma)).*(1+(-4).*a.^2.*(1+(-1).* ...
  a.^2).*cos(alpha.^2).^2.*sech(alpha.^2).^2.*sin(phi).^2).^(-1).*(( ...
  -1).*sin(alpha.^2.*(1+(-1).*gamma))+sinh(alpha.^2.*(1+(-1).*gamma) ...
  )).*sinh(alpha.^2.*gamma)+(1/2).*sech(alpha.^2).*(1+(-2).*a.*(1+( ...
  -1).*a.^2).^(1/2).*cos(phi).*csch(alpha.^2.*gamma).*sin(alpha.^2.* ...
  gamma)).*(sin(alpha.^2.*(1+(-1).*gamma))+sinh(alpha.^2.*(1+(-1).* ...
  gamma))).*sinh(alpha.^2.*gamma));
end